### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-final-Data-Dynamos#3]
Dear Data Dynamos Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

Your second score is 10, so your final proposal score is **9.5/10**

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |        3|
| Proposal | 5         |      5  |
| Workflow | 1         |      1  |
| Teamwork | 1         |      1  |
| Total    | 10        |      10  |

**Feedback**: I was slightly confused about whether this will be a Shiny app or written via JavaScript. I'm okay with using D3.js, but the final project should probably be a Shiny app and not an app build from scratch. You can use D3.js in R via the [r2d3 package](https://rstudio.github.io/r2d3/)

**Overall**: a very interesting project, I look forward to seeing the end product.

**Comment by Shakir0585** [comment]
Hi Greg,

Thank you so much for you feedback!

We have made the following changes made to our proposal:
1. We are going to use HTML, CSS and JavaScript for the project. The R Shiny application was for the contingency plan in case we were unable to obtain the original NASA dataset which we had requested for, however since we have since received the data-set, we are going to proceed with the original plan. 
2. We are not going to build an app from scratch, but rather host the asteroid visualization as a website with interactive features as a GitHub page. 

Requesting a regrade on our project proposal.

Thanks and regards,
Data Dynamos
